---
# Pull news from the Galaxy Training Network's RSS feed and add them as
# Galaxy Hub posts.
name: Galaxy Training Network news

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  collect:
    name: Collect news from the Galaxy Training Network
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install dependencies
        run: pip install feedparser pyyaml

      - name: Parse GTN RSS feed
        id: gtn
        run: |
          python utils/gtn-import.py >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: |
          github.event_name != 'pull_request' &&
          steps.gtn.outputs != ''
        uses: peter-evans/create-pull-request@v7
        with:
          title: Import GTN Posts
          branch-suffix: timestamp
          commit-message: Import GTN Posts
          add-paths: content/news/
