---
# Pull news from the Galaxy Training Network's RSS feed and add them as
# Galaxy Hub posts.
name: Galaxy Training Network news

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

jobs:
  collect:
    name: Collect news from the Galaxy Training Network
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r utils/gtn-import-requirements.txt

      - name: Parse GTN RSS feed
        env:
          GTN_NEWS_FEED_URL: https://training.galaxyproject.org/training-material/feed.xml
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_NAME: ${{ github.repository }}
        run: python utils/gtn-import.py
